### ISSUE TITLE
Error when running onlyrat

### ISSUE THREAD

**Issue by concerned-tos** [CosmodiumCS/OnlyRAT#2]
I continuously get the error;
`IndexError: list index out of range`
when running onlyrat, I tried running the python script itself as well.
IndexError: list index out of range
[https://asciinema.org/a/470250](url)

**Comment by CosmodiumCS** [comment]
can you be more specific? what file are you running, what command are you using, etc. also keep in mind this is still in its BETA phases, so I appreciate your help with getting it closer to "bug free"

**Comment by concerned-tos** [comment]
I attached an asciinema link, it shows what I did.
[https://asciinema.org/a/470250](url)

**Comment by CosmodiumCS** [comment]
thanks so much!! fixed it
