### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by Ghostblackout** [CosmodiumCS/OnlyRAT#3]
Hi I did all the stuffs for OnlyRAT and it still dus not send a email

**Comment by CosmodiumCS** [comment]
Sup!! Make sure you have the following and lemme know if there are any more issues:
- I always suggest making a new Gmail for malware and payloads [**but this is optional**]
- [LSA Access](https://myaccount.google.com/lesssecureapps) **enabled**
- the correct gmail credentials in your `smtp-installer.cmd` file

**Comment by Ghostblackout** [comment]
I have all that stuffs nade it dus not send

**Comment by CosmodiumCS** [comment]
Try making a new email with lsa enabled
